### ISSUE TITLE
Plugin not working with FPP 6 due to Python 3

### ISSUE THREAD

**Issue by ShadowLight8** [ShadowLight8/Si4713_FM_RDS#17]
Per PM on https://falconchristmas.com/forum/index.php/board,8.0.html

I am trying to get your plugin to work with the latest FPP install. It seems your plugin is using Python v2 when that version of python has been disabled on the latest linux distros. My suspicion is that because your python version is on V2 and not V3 is why I cannot get it to work. I did try installing and running the "2to3" applicaton from apt-get, and it seems to have translated it over (Mostly, I had to fix a couple of "is/is not" statements). It now gives me this error:
```
Traceback (most recent call last):
  File "/home/fpp/media/plugins/Si4713_FM_RDS/callbacks.py", line 113, in <module>
    logging.debug('Processing done')
BrokenPipeError: [Errno 32] Broken pipe
```

Any ideas as to why this won't work?

**Comment by ShadowLight8** [comment]
The issue was correctly identified that the plugin was written with Python 2 and needs to be updated to Python 3. This will also change the minimum supported version of FPP to 6.0.

**Comment by ShadowLight8** [comment]
Created a Release for the Python 2 version of the plugin for use with FPP before 6.0. Fix pushed. Waiting for confirmation.

**Comment by ShadowLight8** [comment]
Everything has been working on my test setup. Closing.

**Comment by nmbgeek** [comment]
My FPPD isn't starting on 6.2 or 6.1 with current plugin.  These are clean re-images. Any suggestions?

**Comment by ShadowLight8** [comment]
> My FPPD isn't starting on 6.2 or 6.1 with current plugin.  These are clean re-images. Any suggestions?

Hi there! I'll take a look. I've mostly worked with the OS upgrade route, so I'll check fresh images next.

**Comment by nmbgeek** [comment]
> My FPPD isn't starting on 6.2 or 6.1 with current plugin.  These are clean re-images. Any suggestions?
> 
> Hi there! I'll take a look. I've mostly worked with the OS upgrade route, so I'll check fresh images next.

See #18 I opened.  The smbus module is missing.  Installing python3-smbus resolves issue.

**Comment by ShadowLight8** [comment]
Reclosing and shifting to #18
