### ISSUE TITLE
FPPD Does not start FPP 6.1.1/6.2

### ISSUE THREAD

**Issue by nmbgeek** [ShadowLight8/Si4713_FM_RDS#18]
After installing plugin on FPP 6.1.1 and 6.2 FPPD will not restart.  Test on fresh re-images for each of these versions. After removing plugin FPPD will start again.

**Comment by nmbgeek** [comment]
Just did some more troubleshooting and it seems the smbus module is not installed in these versions.  From cli this fixed it and after a reboot everything is working as expected:
`sudo apt install python3-smbus`

**Comment by ShadowLight8** [comment]
Good catch! I've updated the fpp_install.sh script with [ec83050] so it will install python3-smbus automatically at install.

Used code from https://github.com/ShadowLight8/Dynamic_RDS/blob/main/scripts/fpp_install.sh
