### ISSUE TITLE
Missing/partial default file causes issues

### ISSUE THREAD

**Issue by ShadowLight8** [ShadowLight8/Si4713_FM_RDS#2]
If /home/fpp/media/config/plugin.Si4713_FM_RDS is missing, Si4713_RDS_Updater.py has errors.

```
fpp@FPP:~/media/plugins/Si4713_FM_RDS $ sudo ./Si4713_RDS_Updater.py
Traceback (most recent call last):
  File "./Si4713_RDS_Updater.py", line 159, in <module>
    init_actions()
  File "./Si4713_RDS_Updater.py", line 62, in init_actions
    read_config()
  File "./Si4713_RDS_Updater.py", line 55, in read_config
    with open(configfile, 'r') as f:
IOError: [Errno 2] No such file or directory: '/home/fpp/media/config/plugin.Si4713_FM_RDS'
fpp@FPP:~/media/plugins/Si4713_FM_RDS $ cat /home/fpp/media/config/plugin.Si4713_FM_RDS
GPIONumReset = "4"
fpp@FPP:~/media/plugins/Si4713_FM_RDS $ sudo ./Si4713_RDS_Updater.py
Traceback (most recent call last):
  File "./Si4713_RDS_Updater.py", line 159, in <module>
    init_actions()
  File "./Si4713_RDS_Updater.py", line 63, in init_actions
    RDSStation.delay = int(config['StationDelay'])
KeyError: 'StationDelay'
```

**Comment by whybecausewhy** [comment]
Have you had any luck getting this going using FPP 2.x?

**Comment by ShadowLight8** [comment]
I did a bit of testing with FPP v2 beta and once the callbacks were fixed, was able to get it working. I ran out of time to do more with trying to finish and lockdown my Halloween show. I'll try to update for FPP 2.1 between Halloween and Thanksgiving.

For this specific issue, if you go to the config screen and save/change every item, that builds the default file and the error no longer occurs.

**Comment by ShadowLight8** [comment]
Fixed. Added a built in set of defaults to ensure things can run initially.
