### ISSUE TITLE
Frequency of 92.9 doesn't work

### ISSUE THREAD

**Issue by ShadowLight8** [ShadowLight8/Si4713_FM_RDS#3]
From https://falconchristmas.com/forum/index.php/topic,8996.msg92696.html#msg92696

Need to parse or error check frequency to work with 92.9 instead of requiring 92.90.

**Comment by Geoff-Ilmax** [comment]
Just for clarification, the bug is that it requires two decimal places to be defined, but the menu will allow you to put in a single decimal place.  It is not specific to the 92.9 frequency.

**Comment by ShadowLight8** [comment]
Fixed. Works now with or without a trailing zero.
