### ISSUE TITLE
new Update to the plug-in appears to lock up Pi

### ISSUE THREAD

**Issue by scuba** [ShadowLight8/Si4713_FM_RDS#8]
I could not get the FPP to re-start FPPD after the update to the plugin software.  Tried several things, but after I un-installed the plug-in did the problem go away.

**Comment by ShadowLight8** [comment]
I've retested on FPP v3.6.1-7-gd1d56049 by removing and readding the plug in. I think this was originally caused by a bad commit to master that simply broke the plug in.
